name: pr-open
on: [pull_request]
  jobs:
    run-test-suite:
      runs-on: macos-11
      steps:
        - uses: actions/checkout@v2
        - uses: actions/setup-node@v2
          with:
            node-version: '14'
        - run: yarn
        - run: yarn test